name: Linting
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  stylecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
